name: CosmicAuctionHouse
main: cosmicpe\cosmicauctionhouse\Loader
api: 5.0.0
version: 0.0.2
commands:
  ah:
    description: View the auction house
    usage: /ah
    permission: cosmicpe.command.auctionhouse
permissions:
  cosmicpe.command.auctionhouse:
    description: Ability to use /ah command
    default: true
  cosmicpe.command.auctionhouse.logs:
    description: Ability to use /ah logs command
    default: op